# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_productinstance_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
