# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('z', 'зерномучные товары'), ('f', 'фрукты, овощи, грибы'), ('k', 'крахмалопродукты, сахар, мед, кондитерские изделия'), ('p', 'пищевые жиры'), ('m', 'мясо и мясные товары'), ('f', 'рыба, морепродукты, рыбная продукция;'), ('mi', 'молочные продукты;'), ('e', 'яйца и яичные товары;')], default='m', help_text='тип продукта', max_length=1),
        ),
    ]
