# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='количество в граммах')),
            ],
        ),
        migrations.AlterField(
            model_name='productgrade',
            name='description',
            field=models.TextField(help_text='описание сорта', max_length=1000),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductGrade'),
        ),
    ]
